[accounts]
rTestColdWallet1234567890
rTestHotWallet0987654321

[accounts.rTestColdWallet1234567890]
description = "Orinoco Coin Cold Wallet"
contact = "hernan@orinocoin.com"
domain = "orinocoin.com"

[accounts.rTestHotWallet0987654321]
description = "Orinoco Coin Hot Wallet"
contact = "hernan@orinocoin.com"
domain = "orinocoin.com"

[[tokens]]
currency = "ORI"
issuer = "rTestColdWallet1234567890"
metadata = "https://raw.githubusercontent.com/orinococoin/OrinocoCoin-Assets/refs/heads/main/ori_metadata.json"
